export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  USER_PROFILE_EDIT: (id: string) => `/profile/${id}/edit`,
  DEVELOPER_PROFILE: (id: string) => `/developers/${id}`,
  POSTS: '/posts',
  POST_CREATE: '/posts/new',
  POST_DETAIL: (id: string) => `/posts/${id}`,
  POST_EDIT: (id: string) => `/posts/${id}/edit`,
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  STATUS: '/status',
  CHANGELOG: '/changelog',
} as const;
